# Generated by Django 4.2.4 on 2023-08-30 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0002_user_online_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of message read')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_chat.message', verbose_name='message read receipt')),
                ('read_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='read user')),
            ],
        ),
    ]
